# Generated by Django 5.1.4 on 2025-05-01 13:58
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
